[package]
org = "ballerinax"
name = "oracledb"
version = "1.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/oracledb-native-1.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/sql-native-1.0.0-20211008-021900-95abc84.jar"

[[platform.java11.dependency]]
path = "./lib/ojdbc8-12.2.0.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/xdb-21.1.0.0.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/xmlparserv2-12.2.0.1.jar"
scope = "testOnly"
